"use client";

import { FormEvent, useMemo, useState } from "react";

type Theme = "aurora" | "midnight" | "editorial";
type View = "Today" | "Inbox" | "Calendar" | "Tasks" | "Notes" | "Documents" | "Sources" | "Settings";
const events = [{time:"8:30",title:"Morning planning",meta:"30 min · Focus",tone:"green"},{time:"10:00",title:"Product review",meta:"60 min · Meeting",tone:"violet"},{time:"11:30",title:"Deep work",meta:"90 min · Focus",tone:"blue"},{time:"1:00",title:"Lunch",meta:"60 min · Break",tone:"amber"},{time:"3:00",title:"Build Week sprint",meta:"90 min · Project",tone:"coral"}];
const initialTasks = [{id:1,title:"Finish Build Week submission",due:"Today",priority:"High",done:false},{id:2,title:"Reply to Sarah",due:"Today",priority:"Medium",done:false},{id:3,title:"Review Q3 budget",due:"Tomorrow",priority:"Medium",done:false},{id:4,title:"Prepare product deck",due:"Jul 22",priority:"Low",done:true}];
const sources = [{icon:"✉",name:"Gmail",detail:"8 unread",color:"#ea4335"},{icon:"▣",name:"Calendar",detail:"3 events",color:"#4285f4"},{icon:"▤",name:"Notes",detail:"5 recent",color:"#f4b400"},{icon:"▧",name:"Documents",detail:"7 files",color:"#5b7cfa"}];
const viewCopy:Record<View,{title:string;subtitle:string}>={Today:{title:"Good morning, Alex",subtitle:"What needs your attention today?"},Inbox:{title:"Unified inbox",subtitle:"Everything that needs a response, in one place."},Calendar:{title:"Your calendar",subtitle:"A clear view of your time and commitments."},Tasks:{title:"Tasks",subtitle:"Prioritized by urgency, impact, and available time."},Notes:{title:"Notes",subtitle:"Capture ideas and let LifeOS connect the dots."},Documents:{title:"Documents",subtitle:"Ask questions across your important files."},Sources:{title:"Connected sources",subtitle:"Control what LifeOS can read and organize."},Settings:{title:"Settings",subtitle:"Make LifeOS work the way you do."}};

function Icon({name}:{name:string}){const paths:Record<string,React.ReactNode>={Today:<><path d="m3 11 9-8 9 8"/><path d="M5 10v10h14V10"/><path d="M9 20v-6h6v6"/></>,Inbox:<><path d="M4 5h16v14H4z"/><path d="m4 13 4-3 3 3h2l3-3 4 3"/></>,Calendar:<><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/></>,Tasks:<><circle cx="12" cy="12" r="9"/><path d="m8 12 3 3 5-6"/></>,Notes:<><path d="M5 3h14v18H5z"/><path d="M8 8h8M8 12h8M8 16h5"/></>,Documents:<><path d="M6 2h9l4 4v16H6z"/><path d="M14 2v5h5M9 12h6M9 16h6"/></>,Sources:<><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v7c0 1.7 3.6 3 8 3s8-1.3 8-3V5M4 12v7c0 1.7 3.6 3 8 3s8-1.3 8-3v-7"/></>,Settings:<><circle cx="12" cy="12" r="3"/><path d="M19 15a2 2 0 0 0 .4 2l-2.8 2.8a2 2 0 0 0-2-.4A2 2 0 0 0 13.5 21h-4a2 2 0 0 0-1.1-1.6 2 2 0 0 0-2 .4L3.6 17a2 2 0 0 0 .4-2A2 2 0 0 0 2.5 14v-4A2 2 0 0 0 4 9a2 2 0 0 0-.4-2l2.8-2.8a2 2 0 0 0 2 .4A2 2 0 0 0 9.5 3h4a2 2 0 0 0 1.1 1.6 2 2 0 0 0 2-.4L19.4 7a2 2 0 0 0-.4 2 2 2 0 0 0 1.5 1v4A2 2 0 0 0 19 15Z"/></>};return <svg viewBox="0 0 24 24" aria-hidden="true">{paths[name]??paths.Today}</svg>}

export default function Home(){
 const[theme,setTheme]=useState<Theme>(()=>typeof window!=="undefined"?(localStorage.getItem("lifeos-theme") as Theme||"aurora"):"aurora"),[view,setView]=useState<View>("Today"),[tasks,setTasks]=useState(initialTasks),[prompt,setPrompt]=useState(""),[messages,setMessages]=useState<{role:"user"|"ai";text:string}[]>([]),[loading,setLoading]=useState(false),[toast,setToast]=useState("");
 function chooseTheme(next:Theme){setTheme(next);localStorage.setItem("lifeos-theme",next)}
 async function askLifeOS(e:FormEvent,shortcut?:string){e.preventDefault();const text=shortcut??prompt.trim();if(!text||loading)return;setPrompt("");setMessages(m=>[...m,{role:"user",text}]);setLoading(true);try{const res=await fetch("/api/assistant",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text})});const data=await res.json();setMessages(m=>[...m,{role:"ai",text:data.reply}])}catch{setMessages(m=>[...m,{role:"ai",text:"I couldn’t reach the planner. Your existing schedule is still safe."}])}finally{setLoading(false)}}
 function toggleTask(id:number){setTasks(all=>all.map(t=>t.id===id?{...t,done:!t.done}:t))} const completed=useMemo(()=>tasks.filter(t=>t.done).length,[tasks]);const nav:View[]=["Today","Inbox","Calendar","Tasks","Notes","Documents","Sources"];
 return <main className="app-shell" data-theme={theme}><aside className="sidebar"><button className="brand" onClick={()=>setView("Today")}><span className="brand-mark"><i/><i/><i/></span><strong>LifeOS <em>AI</em></strong></button><nav>{nav.map(item=><button key={item} className={view===item?"active":""} onClick={()=>setView(item)}><Icon name={item}/><span>{item}</span>{item==="Inbox"&&<b>8</b>}</button>)}</nav><div className="sidebar-bottom"><button className={view==="Settings"?"active":""} onClick={()=>setView("Settings")}><Icon name="Settings"/><span>Settings</span></button><div className="profile"><span>AM</span><div><strong>Alex Morgan</strong><small>Personal workspace</small></div><b>⌄</b></div></div></aside>
 <section className="workspace"><header className="topbar"><div><span>Sunday, July 19</span><i/><span>☀ 24°C</span></div><div className="top-actions"><button aria-label="Search">⌕</button><button aria-label="Notifications">♢<b>3</b></button><div className="theme-picker" aria-label="Choose theme">{(["aurora","midnight","editorial"] as Theme[]).map(t=><button key={t} className={`${t} ${theme===t?"selected":""}`} onClick={()=>chooseTheme(t)} title={`${t} theme`}/>)}</div></div></header>
 <div className="page-heading"><div><p>{view==="Today"?"Your day at a glance":view}</p><h1>{viewCopy[view].title}</h1><h2>{viewCopy[view].subtitle}</h2></div>{view==="Today"&&<div className="focus-score"><span><b>78</b></span><div><strong>Daily focus score</strong><small>You’re on track for a productive day.</small></div></div>}</div>
 {view==="Today"?<><form className="command-bar" onSubmit={askLifeOS}><span>✦</span><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Ask LifeOS to plan, find, or organize anything…"/><button type="submit" disabled={loading}>{loading?"•••":"↑"}</button></form><div className="quick-actions">{["Plan my afternoon","Summarize unread messages","Find meeting notes","My plans changed"].map(item=><button key={item} onClick={e=>askLifeOS(e,item)}>✦ {item}</button>)}</div>{messages.length>0&&<section className="conversation">{messages.slice(-4).map((m,i)=><div key={i} className={m.role}><b>{m.role==="ai"?"LifeOS":"You"}</b><p>{m.text}</p></div>)}</section>}
 <div className="dashboard-grid"><section className="card timeline-card"><div className="card-head"><div><span className="mini-icon"><Icon name="Calendar"/></span><h3>Today’s timeline</h3></div><button onClick={()=>setView("Calendar")}>View full day →</button></div><div className="timeline">{events.map(ev=><div className={`event ${ev.tone}`} key={ev.time}><time>{ev.time}</time><i/><div><strong>{ev.title}</strong><small>{ev.meta}</small></div></div>)}</div></section>
 <section className="card tasks-card"><div className="card-head"><div><span className="mini-icon"><Icon name="Tasks"/></span><h3>Priority tasks</h3></div><button onClick={()=>setView("Tasks")}>View all →</button></div><TaskList tasks={tasks} toggle={toggleTask}/><div className="completion"><span><i style={{width:`${completed/tasks.length*100}%`}}/></span><small>{completed} of {tasks.length} complete</small></div></section>
 <section className="card sources-card"><div className="card-head"><div><span className="mini-icon"><Icon name="Sources"/></span><h3>Sources</h3></div><button onClick={()=>setView("Sources")}>Manage →</button></div>{sources.map(s=><button className="source" key={s.name} onClick={()=>{setToast(`${s.name} connection opened`);setTimeout(()=>setToast(""),2200)}}><span style={{color:s.color}}>{s.icon}</span><div><strong>{s.name}</strong><small><i/> Connected</small></div><b>{s.detail}</b><em>›</em></button>)}</section></div>
 <section className="insight"><div className="idea">◉</div><div><small>LifeOS insight</small><h3>You have 2 hours of focus time before your next meeting.</h3><p>I protected your deep-work block and moved two low-priority tasks to tomorrow.</p></div><button onClick={e=>askLifeOS(e,"Show me why you changed my schedule")}>See reasoning</button></section></>:<ViewPanel view={view} tasks={tasks} toggle={toggleTask} chooseTheme={chooseTheme} theme={theme}/>}</section>{toast&&<div className="toast">✓ {toast}</div>}</main>
}

function TaskList({tasks,toggle}:{tasks:typeof initialTasks;toggle:(id:number)=>void}){return <div className="task-list">{tasks.map(t=><button className={t.done?"task done":"task"} key={t.id} onClick={()=>toggle(t.id)}><span className="check">{t.done?"✓":""}</span><span><strong>{t.title}</strong><small>{t.due}</small></span><em className={t.priority.toLowerCase()}>{t.priority}</em></button>)}</div>}
function ViewPanel({view,tasks,toggle,chooseTheme,theme}:{view:View;tasks:typeof initialTasks;toggle:(id:number)=>void;chooseTheme:(t:Theme)=>void;theme:Theme}){if(view==="Settings")return <div className="view-grid"><section className="card wide"><h3>Appearance</h3><p>Choose the visual style that feels right for your day.</p><div className="theme-cards">{(["aurora","midnight","editorial"] as Theme[]).map(t=><button key={t} className={`theme-card ${t} ${theme===t?"active":""}`} onClick={()=>chooseTheme(t)}><i/><strong>{t==="editorial"?"Warm Editorial":t[0].toUpperCase()+t.slice(1)}</strong><small>{t==="aurora"?"Calm and luminous":t==="midnight"?"Focused and futuristic":"Warm and human"}</small></button>)}</div></section><section className="card"><h3>AI preferences</h3>{["Ask before changing my calendar","Include breaks in daily plans","Morning briefing"].map(x=><label className="switch-row" key={x}>{x}<input type="checkbox" defaultChecked/><span/></label>)}</section></div>;if(view==="Tasks")return <section className="card wide"><div className="card-head"><h3>All tasks</h3><button>+ Add task</button></div><TaskList tasks={tasks} toggle={toggle}/></section>;if(view==="Sources")return <div className="source-grid">{sources.map(s=><section className="card source-tile" key={s.name}><span style={{color:s.color}}>{s.icon}</span><div><h3>{s.name}</h3><p>{s.detail} available to LifeOS</p></div><button>Connected ✓</button></section>)}</div>;return <div className="view-grid"><section className="card wide empty-state"><span><Icon name={view}/></span><h3>Your {view.toLowerCase()} workspace is ready</h3><p>This prototype keeps sample data local. Connect a source or add an item to start organizing it with LifeOS.</p><button>+ Add to {view}</button></section><section className="card"><h3>Suggested by LifeOS</h3><p>Review the most important items first, then protect a focus block for meaningful work.</p><ul><li>2 items may need a reply</li><li>1 deadline is approaching</li><li>Your afternoon has 90 free minutes</li></ul></section></div>}
